language: node_js
node_js:
  - 12.13.0
os:
  - linux
script:
  - npm run lint
  - npm test
after_script:
  - |
    # Upload coverage to coveralls
    npm install --save-dev coveralls@2.12.0
    coveralls < ./coverage/lcov.info
  - bash ./scripts/create_pull_request.sh
cache:
  directories:
    - node_modules
deploy:
  provider: npm
  email: "YOUR_EMAIL_ADDRESS"
  api_key: "YOUR_AUTH_TOKEN"
  on:
    tags: true
    tag: next
    branch: master
sudo: false
