version: '3.3'

services:
  web:
    build:
      context: ..
      dockerfile: example/Dockerfile
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
    - MINIO_HOST=minio
    - MINIO_PORT=9000
    - AWS_S3_BUCKET=barfoo
    - AWS_S3_ACCESS_KEY_ID=admin
    - AWS_S3_SECRET_ACCESS_KEY=password
    - AWS_S3_REGION=eu-central-1
    - AWS_S3_ENDPOINT=http://minio:9000/barfoo
    - POSTGRES_URL=postgres://postgres:postgres@pg:5432/postgres
    networks:
    - web
    depends_on:
    - pg
    - minio
    command: node example/app.js
  minio:
    restart: always
    image: minio/minio
    environment:
    - MINIO_ACCESS_KEY=admin
    - MINIO_SECRET_KEY=password
    networks:
    - web
    command: server /export
  pg:
    restart: always
    image: postgres:9.6
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    networks:
    - web

networks:
  web: